dependencies = []
description = "Fork of the official GitHub Action for golangci-lint"
flags = ["tools"]
languages = ["javascript"]
owner = "team-infrastructure-services@scalingo.com"
team = "IST"
tier = 1
version = "1.1.2"
